// ===== Contenu de l'aventure WMG (8 chapitres) =====
const FORMATION = {
  mascot: { name:"Nono", emoji:"🤖" },
  chapters: [

  // ---------- CHAPITRE 0 : Bienvenue ----------
  { id:0, title:"Bienvenue dans ton usine", sub:"Rencontre ton équipe", emoji:"🏭",
    ready:true, badge:{emoji:"🚀", name:"Aventurier·e", bonus:50},
    steps:[
      {type:'story', emoji:"🤖", wiggle:true, kicker:"Ton aventure commence",
       title:`Salut ! Moi c'est <span class="g">Nono</span> 🤖`,
       msg:`Je vais te guider pas à pas pour ouvrir ton usine à publications. Prêt·e ?`,
       say:`Suis-moi, tu vas voir, c'est facile et rapide !`,
       btns:[{label:"C'est parti 🚀", cls:"primary"}]},
      {type:'story', emoji:"🏭", wiggle:true, kicker:"Le grand objectif",
       title:`Une usine qui publie <span class="g">à ta place</span>`,
       msg:`Sur Instagram. Toute seule. Même quand ton ordinateur est éteint.`,
       say:`Et le meilleur : elle est <b>gratuite</b> à faire tourner.`,
       btns:[{label:"Trop bien, la suite →", cls:"primary"}]},
      {type:'story', emoji:"🤝", kicker:"Chapitre 0",
       title:`On va embaucher <span class="g">3 robots</span>`,
       msg:`Ils ne dorment jamais et ne coûtent rien. Je te les présente ?`,
       say:`Ce sont tes futurs employés. Tu vas les adorer.`,
       btns:[{label:"Présente-les moi", cls:"primary"}]},
      {type:'meet', emoji:"🎨", wiggle:true, kicker:"Robot 1 sur 3",
       title:`Le <span class="g">Dessinateur</span>`,
       msg:`Il fabrique tes belles images de publication. Toi tu écris l'idée, lui il dessine.`,
       say:`Zéro logiciel de design à apprendre. Cool, non ?`,
       btns:[{label:"Robot suivant →", cls:"gold"}]},
      {type:'meet', emoji:"📱", wiggle:true, kicker:"Robot 2 sur 3",
       title:`Le <span class="g">Messager</span>`,
       msg:`Quand une publication est prête, il te fait « ding ! » sur ton téléphone : « On publie ? »`,
       say:`C'est toi qui décides. Toujours.`,
       btns:[{label:"Robot suivant →", cls:"gold"}]},
      {type:'meet', emoji:"📮", wiggle:true, kicker:"Robot 3 sur 3",
       title:`Le <span class="g">Facteur</span>`,
       msg:`Tu réponds « oui », et hop — il poste sur Instagram. Voilà, c'est en ligne.`,
       say:`Trois robots, un seul chef : toi 👑`,
       btns:[{label:"Voir mon usine complète", cls:"gold"}]},
      {type:'story', emoji:"", kicker:"Ton équipe est prête", flow:true,
       title:`Voilà ton <span class="g">usine</span> !`,
       msg:`Le Dessinateur prépare → le Messager te prévient → tu valides 👑 → le Facteur publie.`,
       say:`Tu as tout compris ! Passons à la construction.`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 1 : Tes clés ----------
  { id:1, title:"Tes clés", sub:"Créer (ou retrouver) tes comptes", emoji:"🔑",
    ready:true, badge:{emoji:"🗝️", name:"Gardien·ne des clés", bonus:60},
    steps:[
      {type:'story', emoji:"🔑", wiggle:true, kicker:"Chapitre 1",
       title:`Il te faut quelques <span class="g">clés</span>`,
       msg:`Pour ouvrir l'usine : une adresse email, Instagram, Facebook et GitHub. Mais tu en as peut-être déjà !`,
       say:`On coche ce que tu as déjà, pour ne rien refaire.`,
       btns:[{label:"Voyons ça", cls:"primary"}]},
      {type:'branch', emoji:"📧", kicker:"Ta clé n°1",
       title:`As-tu une <span class="g">adresse email</span> que tu regardes tous les jours ?`,
       say:`Gmail, Outlook, celle de ton entreprise… tout compte.`,
       btns:[{label:"✅ Oui, j'en ai une", cls:"ghost", points:5, skip:1},{label:"❌ Non, pas vraiment", cls:"ghost"}]},
      {type:'action', emoji:"📨", kicker:"Mission · action",
       title:`Crée une adresse <span class="g">Gmail</span>`,
       msg:`Suis les étapes une par une avec les flèches 👇`,
       slider:[
         {src:"shots/gmail/1.png",  cap:"Va sur gmail.com, clique « Créer un compte », puis écris ton prénom."},
         {src:"shots/gmail/2.png",  cap:"Clique sur le bouton bleu « Suivant »."},
         {src:"shots/gmail/3.png",  cap:"Choisis ta date de naissance et ton genre."},
         {src:"shots/gmail/4.png",  cap:"Choisis une adresse Gmail proposée, ou crée la tienne."},
         {src:"shots/gmail/5.png",  cap:"Invente un mot de passe et note-le sur un papier."},
         {src:"shots/gmail/6.png",  cap:"Écris ton numéro de téléphone."},
         {src:"shots/gmail/7.png",  cap:"Sur l'ordinateur, Google affiche un QR code : scanne-le avec ton téléphone."},
         {src:"shots/gmail/8.png",  cap:"Sur ton téléphone, cet écran s'ouvre : appuie sur « Envoyer un SMS »."},
         {src:"shots/gmail/9.png",  cap:"Une fenêtre demande d'ouvrir Messages : appuie sur « Ouvrir »."},
         {src:"shots/gmail/10.png", cap:"Le SMS est déjà écrit : envoie-le avec la flèche verte, sans rien changer."},
         {src:"shots/gmail/11.png", cap:"Autre cas : parfois Google t'envoie plutôt un code par SMS. Alors recopie-le, c'est tout."},
         {src:"shots/gmail/12.png", cap:"De retour sur l'ordinateur : ajoute un e-mail de secours, ou clique « Suivant »."},
         {src:"shots/gmail/13.png", cap:"Clique sur « J'accepte »."},
         {src:"shots/gmail/14.png", cap:"Bravo ! Voici ta boîte mail. « Nouveau message » sert à écrire un e-mail."}
       ],
       say:`Note bien le mot de passe dans un carnet !`,
       hint:`Google demandera ton numéro pour t'envoyer un code — c'est normal.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"📷", kicker:"Ta clé n°2",
       title:`As-tu déjà un <span class="g">compte Instagram</span> pour ton activité ?`,
       say:`Beaucoup de gens en ont déjà un — bon point !`,
       btns:[{label:"✅ Oui, j'en ai un", cls:"ghost", points:5, skip:1},{label:"❌ Non, pas encore", cls:"ghost"}]},
      {type:'action', emoji:"📲", kicker:"Mission · action",
       title:`Crée ton <span class="g">Instagram</span>`,
       msg:`Sur ton téléphone. Suis les étapes une par une 👇`,
       slider:[
         {src:"shots/instagram/1.png", cap:"Dans le magasin d'applis, cherche « Instagram » et appuie sur « Obtenir »."},
         {src:"shots/instagram/2.png", cap:"Ouvre l'application et appuie sur « Créer un compte »."},
         {src:"shots/instagram/3.png", cap:"Écris ton adresse e-mail (celle que tu viens de créer), puis « Suivant »."},
         {src:"shots/instagram/4.png", cap:"Regarde tes mails et tape le code à 6 chiffres reçu."},
         {src:"shots/instagram/5.png", cap:"Invente un mot de passe et note-le sur ton papier."},
         {src:"shots/instagram/6.png", cap:"Choisis ta date de naissance."},
         {src:"shots/instagram/7.png", cap:"Écris ton nom (ou le nom de ton activité)."},
         {src:"shots/instagram/8.png", cap:"Choisis ton nom d'utilisateur (ton @, ex. @ton.activite)."},
         {src:"shots/instagram/9.png", cap:"Bravo ! Ton compte Instagram est créé. 🎉"}
       ],
       say:`Mets une photo de profil et une phrase qui dit ce que tu fais 😊`,
       hint:`App Store pour iPhone · Play Store pour Android.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"💼", kicker:"Réglage important",
       title:`Ton Instagram est-il en <span class="g">« compte professionnel »</span> ?`,
       msg:`(Tu vois un bouton « Tableau de bord professionnel » sur ton profil ?)`,
       say:`Ce réglage est <b>obligatoire</b> pour l'automatisation.`,
       btns:[{label:"✅ Oui, déjà fait", cls:"ghost", points:5, skip:1},{label:"❌ Non / je ne sais pas", cls:"ghost"}]},
      {type:'action', emoji:"🔧", kicker:"Mission · action",
       title:`Passe en <span class="g">compte professionnel</span>`,
       msg:`Instagram : Profil → ☰ → Paramètres → « Passer à un compte professionnel » → « Entreprise ».`,
       say:`S'il propose de connecter Facebook, choisis « Ignorer » — on le fera au bon moment.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"👥", kicker:"Ta clé n°3",
       title:`As-tu un <span class="g">compte Facebook</span> (même inutilisé) ?`,
       say:`Il sert juste de « badge d'accès » chez Meta. Il restera vide.`,
       btns:[{label:"✅ Oui, j'en ai un", cls:"ghost", points:5, skip:1},{label:"❌ Non", cls:"ghost"}]},
      {type:'action', emoji:"📘", kicker:"Mission · action",
       title:`Crée un compte <span class="g">Facebook</span>`,
       msg:`Sur facebook.com → « Créer un compte ». Ton vrai nom et l'email du projet.`,
       say:`Ce compte ne postera jamais rien. C'est ta clé d'entrée chez Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"🐙", kicker:"Ta clé n°4",
       title:`As-tu déjà un compte <span class="g">GitHub</span> ?`,
       say:`La plupart des gens n'en ont pas — c'est normal.`,
       btns:[{label:"✅ Oui", cls:"ghost", points:5, skip:1},{label:"❌ Non", cls:"ghost"}]},
      {type:'action', emoji:"🏢", kicker:"Mission · action",
       title:`Crée ton compte <span class="g">GitHub</span>`,
       msg:`Va sur github.com et clique « Sign up ». La page est en anglais — suis la main 👇`,
       shot:"shots/s-github.gif",
       say:`GitHub, c'est le bâtiment gratuit où vivront tes 3 robots.`,
       hint:`Email = e-mail · Password = mot de passe · Username = pseudo. GitHub t'envoie ensuite un code à 8 chiffres par email.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔔", kicker:"Dernière clé",
       title:`Installe l'<span class="g">app GitHub</span> sur ton téléphone`,
       msg:`C'est ta télécommande : c'est là que tu diras « oui, publie ! ».`,
       say:`Quand elle demande les notifications, dis OUI — c'est le Messager !`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"🎯", kicker:"Récap",
       title:`Tes clés sont <span class="g">prêtes</span> !`,
       msg:`Email ✓ · Instagram pro ✓ · Facebook ✓ · GitHub ✓ · app mobile ✓`,
       say:`Le plus administratif est déjà derrière toi !`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 2 : Ton style ----------
  { id:2, title:"Ton style", sub:"Tes couleurs, ton logo, tes slides", emoji:"🎨",
    ready:true, badge:{emoji:"🖌️", name:"Artiste", bonus:55},
    steps:[
      {type:'story', emoji:"🎨", wiggle:true, kicker:"Chapitre 2",
       title:`On <span class="g">habille</span> ton usine`,
       msg:`Tu vas créer tes visuels de publication ici même, dans cette page. Rien à installer : pas de Canva, pas de logiciel, pas de code.`,
       say:`Tout se passe dans le site. Tu ne le quittes jamais 😊`,
       btns:[{label:"Montre-moi", cls:"primary"}]},
      {type:'story', emoji:"🖌️", kicker:"Comment ça marche",
       title:`Un <span class="g">éditeur en ligne</span>, juste en dessous`,
       msg:`Dans un instant, ton studio s'ouvre directement dans cette page : tu choisis tes couleurs, tu mets ton logo, et tu vois ta slide changer en direct.`,
       say:`Comme jouer avec des feutres — mais sur écran.`,
       btns:[{label:"Ouvre mon studio 🎨", cls:"gold"}]},
      {type:'action', emoji:"🎨", kicker:"À toi de jouer · dans le site",
       embed:"editeur.html",
       title:`Personnalise ta <span class="g">slide</span>`,
       msg:`Change tes 4 couleurs, mets ton @ Instagram et ton logo. La slide à droite se met à jour toute seule. Quand ça te plaît : « Valider » puis « Télécharger ».`,
       say:`Prends ton temps, essaie des couleurs. Rien ne peut casser !`,
       hint:`Astuce : reprends les couleurs de ton logo ou de ton site pour rester cohérent.`,
       btns:[{label:"Mon kit est téléchargé ✓", cls:"green", points:20}]},
      {type:'story', emoji:"✨", kicker:"Bravo",
       title:`Ta <span class="g">première slide</span> existe !`,
       msg:`À tes couleurs, avec ton logo, sans aucun logiciel de design — et sans quitter le site. Tu vois la puissance du truc ?`,
       say:`Le Dessinateur connaît maintenant ton style.`,
       btns:[{label:"Une dernière chose →", cls:"primary"}]},
      {type:'story', emoji:"📐", kicker:"La règle d'or",
       title:`Un bon carrousel = <span class="g">1 seule idée</span>`,
       msg:`Slide 1 : une promesse. Puis l'idée pas à pas. Avant la fin : une question quiz. Dernière : un petit récap.`,
       say:`Simple à retenir, simple à faire.`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 3 : Les clés magiques de Meta ----------
  { id:3, title:"Les clés magiques de Meta", sub:"Le sésame qui publie pour toi", emoji:"🗝️",
    ready:true, badge:{emoji:"🔓", name:"Passe-partout", bonus:80},
    steps:[
      {type:'story', emoji:"🏛️", wiggle:true, kicker:"Chapitre 3 · le grand boss",
       title:`Les <span class="g">autorisations</span> de Meta`,
       msg:`C'est LE chapitre que tout le monde rate. Mais pas toi : je reste avec toi à chaque guichet.`,
       say:`C'est de l'administratif — pas difficile, juste précis. Respire 😊`,
       btns:[{label:"Je suis prêt·e", cls:"primary"}]},
      {type:'story', emoji:"⚠️", kicker:"Le piège à connaître",
       title:`Ignore le <span class="g">bouton fantôme</span>`,
       msg:`Une page de Meta promet un bouton « Générer un token » qui n'apparaît jamais. Des gens y perdent des heures. Nous, on passe par la bonne porte : le Business Manager.`,
       say:`Si tu tombes sur cette page piège : ferme-la, reviens ici.`,
       btns:[{label:"Noté !", cls:"primary"}]},
      {type:'action', emoji:"📋", kicker:"Guichet 1",
       title:`Crée ton <span class="g">app Meta</span>`,
       msg:`Sur developers.facebook.com (connecté à Facebook) → « Créer une app » → cas d'usage « Instagram ».`,
       say:`C'est ton dossier officiel à la mairie Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🗄️", kicker:"Guichet 2",
       title:`Crée ton <span class="g">portefeuille business</span>`,
       msg:`Sur business.facebook.com → « Créer un compte » → nom de ton entreprise + email du projet.`,
       say:`C'est le classeur qui regroupe tout ce qui t'appartient chez Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔐", kicker:"Guichet 2 bis",
       title:`Active la <span class="g">double sécurité</span>`,
       msg:`Facebook → Paramètres → Sécurité → « Authentification à deux facteurs » → SMS → valide le code.`,
       say:`Meta l'exige pour confier des clés d'automatisation. Logique : ce sont les clés du camion.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"📷", kicker:"Guichet 3 · 🔑 clé 1/2",
       title:`<span class="g">Revendique</span> ton Instagram`,
       msg:`Business Manager → ⚙️ Paramètres → Comptes → Comptes Instagram → « Ajouter » → connecte @toncompte.`,
       say:`⚠️ Note bien le long numéro à 17 chiffres qui s'affiche — c'est ta 1re clé !`,
       btns:[{label:"Compte revendiqué + numéro noté ✓", cls:"green", points:15}]},
      {type:'action', emoji:"🤖", kicker:"Guichet 4",
       title:`Embauche ton <span class="g">facteur</span>`,
       msg:`⚙️ → Utilisateurs système → « Ajouter » → nom « Facteur » → puis « Affecter des éléments » : ton compte Instagram ET ton app.`,
       say:`C'est ton employé-robot officiel chez Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"📄", kicker:"L'étape magique",
       title:`La <span class="g">Page Facebook</span>, l'adaptateur`,
       msg:`Meta oblige à passer par une Page Facebook (qui restera vide). Sans elle, le facteur reste à la porte.`,
       say:`C'est LA pièce que tout le monde oublie. Toi, tu la mets 😉`,
       btns:[{label:"On la crée", cls:"primary"}]},
      {type:'action', emoji:"🔗", kicker:"Guichet 5",
       title:`Crée la Page + <span class="g">lie-la</span> à Instagram`,
       msg:`Business Manager → Comptes → Pages → crée une Page. Puis dans l'app Instagram : Modifier le profil → Page → connecte ta Page.`,
       say:`Vérifie : dans les « éléments connectés » de la Page, ton Instagram apparaît. Le courant passe !`,
       btns:[{label:"Page créée et liée ✓", cls:"green", points:15}]},
      {type:'action', emoji:"🔑", kicker:"Guichet 6 · 🔑 clé 2/2",
       title:`Génère le <span class="g">token permanent</span>`,
       msg:`⚙️ → Utilisateurs système → Facteur → « Générer un token » → ton app → expiration « Jamais » → coche les 6 permissions → Générer → COPIE-le en lieu sûr.`,
       say:`Ce badge n'expire jamais. Configuré une fois, tranquille pour toujours 🎯`,
       btns:[{label:"Token généré et sauvegardé ✓", cls:"green", points:20}]},
      {type:'action', emoji:"🏆", kicker:"Le test de la victoire",
       title:`<span class="g">Teste</span> tes clés`,
       msg:`Double-clique « TESTER-TOKEN » du kit → colle ton token + ton numéro à 17 chiffres. Si tout est bon : ton nom de compte s'affiche + « quota : 0 ».`,
       say:`Si tu vois ton nom de compte : tu as réussi le plus dur. Chapeau !`,
       btns:[{label:"Ça affiche mon compte ✓", cls:"green", points:20}]},
      {type:'story', emoji:"🎉", kicker:"Énorme",
       title:`Tu as réussi ce que <span class="g">90 % abandonnent</span>`,
       msg:`Le plus dur est officiellement derrière toi. La suite, c'est de l'assemblage.`,
       say:`Je suis fier de toi. Vraiment.`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 4 : L'étagère à images ----------
  { id:4, title:"L'étagère à images", sub:"Héberger tes visuels, gratuitement", emoji:"📦",
    ready:true, badge:{emoji:"📚", name:"Rangé·e", bonus:45},
    steps:[
      {type:'story', emoji:"📦", wiggle:true, kicker:"Chapitre 4 · le plus court",
       title:`Un <span class="g">point de retrait</span> pour tes images`,
       msg:`Quand le facteur publie, Instagram veut aller chercher l'image lui-même, à une adresse. On lui crée cette étagère.`,
       say:`5 minutes, promis. Le chapitre le plus rapide.`,
       btns:[{label:"Allons-y", cls:"primary"}]},
      {type:'action', emoji:"📁", kicker:"Mission · action",
       title:`Crée un dépôt public <span class="g">« mes-images »</span>`,
       msg:`Sur github.com → bouton « + » → « New repository » → nom « mes-images » → coche « Public » et « Add a README » → Create.`,
       say:`« Dépôt » = un dossier hébergé sur internet. Rien de plus.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"👁️", kicker:"Public, mais sans danger",
       title:`« Public », <span class="g">est-ce risqué</span> ? Non.`,
       msg:`On n'y met que des images en cours de publication — des images qui seront de toute façon publiques sur ton profil 10 secondes plus tard. Jamais de secret ici.`,
       say:`Tes clés, elles, ne vont JAMAIS ici. On les garde ailleurs.`,
       btns:[{label:"Rassuré·e", cls:"primary"}]},
      {type:'action', emoji:"🔗", kicker:"Petit test",
       title:`Teste une <span class="g">adresse d'image</span>`,
       msg:`Dans mes-images → « Add file » → glisse une image → « Commit ». Clique dessus → bouton « Raw » : l'image s'ouvre seule, avec une adresse. C'est ça qu'Instagram viendra chercher.`,
       say:`Ouvre cette adresse en navigation privée : elle s'affiche sans connexion. Parfait !`,
       btns:[{label:"L'image s'ouvre ✓", cls:"green", points:10}]},
      {type:'story', emoji:"✅", kicker:"Récap",
       title:`Ton étagère est <span class="g">ouverte</span>`,
       msg:`Le facteur saura où déposer les images pour qu'Instagram les récupère.`,
       say:`Prochain chapitre : ta toute première publication 🚀`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 5 : Ta première publication ----------
  { id:5, title:"Ta première publication", sub:"Le grand moment 🎉", emoji:"🚀",
    ready:true, badge:{emoji:"🥇", name:"Première fois", bonus:70},
    steps:[
      {type:'story', emoji:"🚀", wiggle:true, kicker:"Chapitre 5 · le grand jour",
       title:`Prépare ta <span class="g">première publication</span>`,
       msg:`Bonne nouvelle : aucun terminal, aucun logiciel, aucune ligne de code. Tout se prépare ici, dans le site, comme tu l'as fait pour ta slide.`,
       say:`Zéro geste technique. Promis 🤖`,
       btns:[{label:"Allons-y", cls:"primary"}]},
      {type:'story', emoji:"🧩", kicker:"Rappel simple",
       title:`Un carrousel = <span class="g">quelques slides</span>`,
       msg:`Une promesse, l'idée expliquée pas à pas, une petite question, un récap. Tu écris juste les textes — le Dessinateur fait le reste.`,
       say:`Toi les idées, les robots le design.`,
       btns:[{label:"Compris", cls:"primary"}]},
      {type:'action', emoji:"✍️", kicker:"À toi de jouer · dans le site",
       embed:"editeur.html",
       title:`Écris ton <span class="g">premier carrousel</span>`,
       msg:`Reprends ton studio : garde tes couleurs, et remplis les textes de tes slides. Regarde l'aperçu se remplir en direct. Quand c'est bon : « Valider » puis « Télécharger ».`,
       say:`C'est le même studio qu'au chapitre 2 — tu connais déjà !`,
       hint:`Pas d'idée ? Reprends l'exemple fourni et change juste quelques mots pour t'entraîner.`,
       btns:[{label:"Mon carrousel est prêt ✓", cls:"green", points:20}]},
      {type:'story', emoji:"📮", kicker:"Et maintenant ?",
       title:`Qui va le <span class="g">publier</span> ?`,
       msg:`Pas toi à la main, et surtout pas via un terminal. C'est ton usine de robots qui va s'en charger — et tu valideras d'un seul clic depuis ton téléphone.`,
       say:`On construit cette usine au prochain chapitre. C'est là que la magie opère 🎩`,
       btns:[{label:"Une chose à savoir avant →", cls:"primary"}]},
      {type:'story', emoji:"🔐", kicker:"Tes clés, en sécurité",
       title:`Tes clés vivront dans un <span class="g">coffre en ligne</span>`,
       msg:`Ton token du chapitre 3 ne se colle JAMAIS dans un fichier sur ton ordinateur. Il ira dans un coffre-fort chiffré de ton usine (on le fait ensemble au chapitre 6).`,
       say:`Tes clés, personne ne les voit. Même pas moi 🔒`,
       btns:[{label:"Rassurant", cls:"primary"}]},
      {type:'story', emoji:"🎉", kicker:"Prêt·e",
       title:`Ton contenu est <span class="g">prêt à partir</span> !`,
       msg:`Tu as tes visuels et ton premier carrousel — tout ça sans jamais quitter le site. Il ne manque que l'usine qui appuie sur « publier » à ta place.`,
       say:`Le meilleur chapitre arrive : ton usine autonome 🏭`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 6 : L'usine cloud ----------
  { id:6, title:"L'usine qui tourne seule", sub:"Ordinateur éteint, ça publie", emoji:"☁️",
    ready:true, badge:{emoji:"🏭", name:"Patron·ne d'usine", bonus:75},
    steps:[
      {type:'story', emoji:"☁️", wiggle:true, kicker:"Chapitre 6",
       title:`Ton ordinateur peut <span class="g">dormir</span>`,
       msg:`Ton contenu est prêt (chapitre 5). Maintenant, on embauche tes robots chez GitHub : ils prépareront et publieront tout seuls, même ton ordinateur éteint.`,
       say:`GitHub prête des ordinateurs gratuits qui obéissent à un réveil-matin.`,
       btns:[{label:"On y va !", cls:"primary"}]},
      {type:'action', emoji:"🏢", kicker:"Mission · action",
       title:`Crée le dépôt privé <span class="g">« mon-usine »</span>`,
       msg:`github.com → « + » → New repository → nom « mon-usine » → coche « Private » 🔒 → Create.`,
       say:`Privé : ta stratégie de contenu ne regarde personne.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"📤", kicker:"Mission · action",
       title:`Dépose les <span class="g">fichiers du kit</span>`,
       msg:`Dans « mon-usine » → Add file → Upload → glisse le kit que tu as téléchargé (celui de l'éditeur) → Commit.`,
       say:`Ce kit ne contient aucune clé — tes clés, on les met juste après, dans le coffre.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔒", kicker:"Le coffre-fort",
       title:`Range tes clés dans les <span class="g">secrets</span>`,
       msg:`mon-usine → Settings → Secrets and variables → Actions → crée tes secrets (token, identifiant, étagère…), un par un, avec les noms exacts fournis.`,
       say:`Un coffre chiffré : les robots s'en servent, personne ne peut le relire.`,
       btns:[{label:"Secrets créés ✓", cls:"green", points:15}]},
      {type:'action', emoji:"🤖", kicker:"Mission · action",
       title:`Réveille tes <span class="g">robots</span>`,
       msg:`Onglet « Actions » de ton dépôt → si on te demande d'activer les workflows, clique. Puis lance un test : « Préparer le prochain carrousel » → Run workflow.`,
       say:`Rond jaune → coche verte = ton robot a travaillé tout seul !`,
       btns:[{label:"Le test passe au vert ✓", cls:"green", points:15}]},
      {type:'story', emoji:"📱", kicker:"Ding !",
       title:`Un <span class="g">ticket</span> arrive sur ton téléphone`,
       msg:`Le Messager t'envoie une notification : « Carrousel prêt ». Tu ouvres, tu vois les aperçus + la légende.`,
       say:`C'est le moment où TU décides. Depuis ton canapé.`,
       btns:[{label:"Je vois le ticket", cls:"primary"}]},
      {type:'action', emoji:"✅", kicker:"La magie",
       title:`Écris <span class="g">/publier</span> dans le ticket`,
       msg:`En bas du ticket, commente : /publier → envoie. 2 minutes plus tard : « ✅ Publié ! ». Et ton ordinateur est ÉTEINT.`,
       say:`Un ordinateur gratuit de GitHub vient de publier pour toi, puis s'est éteint. 🤯`,
       btns:[{label:"C'est publié, ordi éteint ✓", cls:"green", points:20}]},
      {type:'story', emoji:"🏭", kicker:"Énorme",
       title:`Ton usine est <span class="g">autonome</span> !`,
       msg:`Tous les 3 jours, elle prépare, te demande, et publie. Toi, tu valides depuis ton téléphone. En vacances, au ski, peu importe.`,
       say:`Tu es officiellement patron·ne d'usine 🏭`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 7 : Faire vivre ton usine ----------
  { id:7, title:"Faire vivre ton usine", sub:"Créer TON contenu · dépannage", emoji:"⚙️",
    ready:true, badge:{emoji:"🎓", name:"Diplômé·e", bonus:100},
    steps:[
      {type:'story', emoji:"⚙️", wiggle:true, kicker:"Dernier chapitre",
       title:`Le quotidien du <span class="g">patron</span>`,
       msg:`Ton usine tourne. Voyons comment la nourrir, la dépanner, et la garder en sécurité.`,
       say:`Le chapitre que tu rouvriras souvent. Gardons-le simple.`,
       btns:[{label:"C'est parti", cls:"primary"}]},
      {type:'story', emoji:"📓", kicker:"Le tableau de bord",
       title:`Le <span class="g">journal de production</span>`,
       msg:`Un fichier tenu à jour par les robots eux-mêmes : il dit où en est chaque carrousel (en file, en validation, publié). C'est la 1re chose à regarder.`,
       say:`« Où en est-on ? » → un coup d'œil au journal.`,
       btns:[{label:"Compris", cls:"primary"}]},
      {type:'action', emoji:"✍️", kicker:"Mission · action",
       title:`Crée <span class="g">TON</span> premier carrousel`,
       msg:`Duplique le dossier d'exemple, renomme-le, et change juste les textes de chaque slide (comme dans un formulaire). Dépose-le dans « mon-usine ». C'est tout !`,
       say:`Tu fournis les idées ; l'usine fait le design et la publication.`,
       btns:[{label:"J'ai créé mon carrousel ✓", cls:"green", points:15}]},
      {type:'story', emoji:"💡", kicker:"L'astuce qui va vite",
       title:`Fais-toi aider par une <span class="g">IA</span>`,
       msg:`Donne à un assistant IA (ChatGPT, Claude…) ta structure (promesse → idée → quiz → récap) + ton sujet, et il t'écrit les textes en 2 minutes. Tu gardes ton style.`,
       say:`Prépare 2-3 carrousels le dimanche : tu as une semaine d'avance.`,
       btns:[{label:"Bonne idée", cls:"primary"}]},
      {type:'story', emoji:"🛠️", kicker:"Pas de panique",
       title:`Les 5 <span class="g">pannes</span> classiques`,
       msg:`« Media ID not available » = patiente. Run rouge = souvent un secret mal orthographié. Pas de notif = réactive-les dans l'app. Le kit contient un tableau symptôme → remède.`,
       say:`Rien de ce que tu cliques ne casse définitivement. Le pire = régénérer un token (5 min).`,
       btns:[{label:"Rassurant", cls:"primary"}]},
      {type:'story', emoji:"📌", kicker:"La seule action manuelle",
       title:`Épingle le <span class="g">commentaire quiz</span>`,
       msg:`L'usine poste la réponse du quiz en commentaire, mais ne peut pas l'épingler. 10 secondes : appui long dessus → Épingler. Voilà.`,
       say:`La seule chose qui reste vraiment la tienne.`,
       btns:[{label:"Noté", cls:"primary"}]},
      {type:'story', emoji:"🔒", kicker:"Sécurité",
       title:`Les 4 <span class="g">commandements</span> des clés`,
       msg:`1) Ton token ne se partage jamais. 2) Il ne va jamais dans le dépôt public. 3) Un doute ? Révoque et régénère. 4) Double authentification active à vie.`,
       say:`« Le support Instagram » qui te demande ton token, c'est TOUJOURS une arnaque.`,
       btns:[{label:"Compris et retenu", cls:"primary"}]},
      {type:'story', emoji:"🎓", wiggle:true, kicker:"🏆 LA FIN",
       title:`Tu es <span class="g">diplômé·e</span> de l'usine !`,
       msg:`Ton compte publie désormais avec la régularité d'une horloge — et c'est exactement ce qu'Instagram récompense. Bravo, vraiment. À toi de jouer 🚀`,
       say:`J'ai adoré t'accompagner. Fier de toi ! — Nono 🤖`,
       btns:[{label:"Recevoir mon diplôme 🎓", cls:"green"}]},
    ]},

]};
