// ===== Contenu de l'aventure WMG (8 chapitres) =====
const FORMATION = {
  mascot: { name:"Nono", emoji:"🤖" },
  chapters: [

  // ---------- CHAPITRE 0 : Bienvenue ----------
  { id:0, title:"Bienvenue dans ton usine", sub:"Rencontre ton équipe", emoji:"🏭",
    ready:true, badge:{emoji:"🚀", name:"Aventurier·e", bonus:50},
    steps:[
      {type:'story', emoji:"🤖", wiggle:true, kicker:"Ton aventure commence",
       title:`Salut ! Moi c'est <span class="g">Nono</span> 🤖`,
       msg:`Je vais te guider pas à pas pour ouvrir ton usine à publications. Prêt·e ?`,
       say:`Suis-moi, tu vas voir, c'est facile et rapide !`,
       btns:[{label:"C'est parti 🚀", cls:"primary"}]},
      {type:'story', emoji:"🏭", wiggle:true, kicker:"Le grand objectif",
       title:`Une usine qui publie <span class="g">à ta place</span>`,
       msg:`Sur Instagram. Toute seule. Même quand ton ordinateur est éteint.`,
       say:`Et le meilleur : elle est <b>gratuite</b> à faire tourner.`,
       btns:[{label:"Trop bien, la suite →", cls:"primary"}]},
      {type:'story', emoji:"🤝", kicker:"Chapitre 0",
       title:`On va embaucher <span class="g">3 robots</span>`,
       msg:`Ils ne dorment jamais et ne coûtent rien. Je te les présente ?`,
       say:`Ce sont tes futurs employés. Tu vas les adorer.`,
       btns:[{label:"Présente-les moi", cls:"primary"}]},
      {type:'meet', emoji:"🎨", wiggle:true, kicker:"Robot 1 sur 3",
       title:`Le <span class="g">Dessinateur</span>`,
       msg:`Il fabrique tes belles images de publication. Toi tu écris l'idée, lui il dessine.`,
       say:`Zéro logiciel de design à apprendre. Cool, non ?`,
       btns:[{label:"Robot suivant →", cls:"gold"}]},
      {type:'meet', emoji:"📱", wiggle:true, kicker:"Robot 2 sur 3",
       title:`Le <span class="g">Messager</span>`,
       msg:`Quand une publication est prête, il te fait « ding ! » sur ton téléphone : « On publie ? »`,
       say:`C'est toi qui décides. Toujours.`,
       btns:[{label:"Robot suivant →", cls:"gold"}]},
      {type:'meet', emoji:"📮", wiggle:true, kicker:"Robot 3 sur 3",
       title:`Le <span class="g">Facteur</span>`,
       msg:`Tu réponds « oui », et hop — il poste sur Instagram. Voilà, c'est en ligne.`,
       say:`Trois robots, un seul chef : toi 👑`,
       btns:[{label:"Voir mon usine complète", cls:"gold"}]},
      {type:'story', emoji:"", kicker:"Ton équipe est prête", flow:true,
       title:`Voilà ton <span class="g">usine</span> !`,
       msg:`Le Dessinateur prépare → le Messager te prévient → tu valides 👑 → le Facteur publie.`,
       say:`Tu as tout compris ! Passons à la construction.`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 1 : Tes clés ----------
  { id:1, title:"Tes clés", sub:"Créer (ou retrouver) tes comptes", emoji:"🔑",
    ready:true, badge:{emoji:"🗝️", name:"Gardien·ne des clés", bonus:60},
    steps:[
      {type:'story', emoji:"🔑", wiggle:true, kicker:"Chapitre 1",
       title:`Il te faut quelques <span class="g">clés</span>`,
       msg:`Pour ouvrir l'usine : une adresse email, Instagram, Facebook et GitHub. Mais tu en as peut-être déjà !`,
       say:`On coche ce que tu as déjà, pour ne rien refaire.`,
       btns:[{label:"Voyons ça", cls:"primary"}]},
      {type:'branch', emoji:"📧", kicker:"Ta clé n°1",
       title:`As-tu une <span class="g">adresse email</span> que tu regardes tous les jours ?`,
       say:`Gmail, Outlook, celle de ton entreprise… tout compte.`,
       btns:[{label:"✅ Oui, j'en ai une", cls:"ghost", points:5, skip:1},{label:"❌ Non, pas vraiment", cls:"ghost"}]},
      {type:'action', emoji:"📨", kicker:"Mission · action",
       title:`Crée une adresse <span class="g">Gmail</span>`,
       msg:`Va sur gmail.com → « Créer un compte ». Choisis une adresse sérieuse (ex. contact.tonentreprise@gmail.com).`,
       say:`Note bien le mot de passe dans un carnet !`,
       hint:`Google demandera ton numéro pour t'envoyer un code — c'est normal.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"📷", kicker:"Ta clé n°2",
       title:`As-tu déjà un <span class="g">compte Instagram</span> pour ton activité ?`,
       say:`Beaucoup de gens en ont déjà un — bon point !`,
       btns:[{label:"✅ Oui, j'en ai un", cls:"ghost", points:5, skip:1},{label:"❌ Non, pas encore", cls:"ghost"}]},
      {type:'action', emoji:"📲", kicker:"Mission · action",
       title:`Installe <span class="g">Instagram</span>`,
       msg:`Sur ton téléphone : magasin d'applis → cherche « Instagram » → installe → crée ton compte avec ton email.`,
       say:`Mets une photo de profil et une phrase qui dit ce que tu fais 😊`,
       hint:`App Store pour iPhone · Play Store pour Android.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"💼", kicker:"Réglage important",
       title:`Ton Instagram est-il en <span class="g">« compte professionnel »</span> ?`,
       msg:`(Tu vois un bouton « Tableau de bord professionnel » sur ton profil ?)`,
       say:`Ce réglage est <b>obligatoire</b> pour l'automatisation.`,
       btns:[{label:"✅ Oui, déjà fait", cls:"ghost", points:5, skip:1},{label:"❌ Non / je ne sais pas", cls:"ghost"}]},
      {type:'action', emoji:"🔧", kicker:"Mission · action",
       title:`Passe en <span class="g">compte professionnel</span>`,
       msg:`Instagram : Profil → ☰ → Paramètres → « Passer à un compte professionnel » → « Entreprise ».`,
       say:`S'il propose de connecter Facebook, choisis « Ignorer » — on le fera au bon moment.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"👥", kicker:"Ta clé n°3",
       title:`As-tu un <span class="g">compte Facebook</span> (même inutilisé) ?`,
       say:`Il sert juste de « badge d'accès » chez Meta. Il restera vide.`,
       btns:[{label:"✅ Oui, j'en ai un", cls:"ghost", points:5, skip:1},{label:"❌ Non", cls:"ghost"}]},
      {type:'action', emoji:"📘", kicker:"Mission · action",
       title:`Crée un compte <span class="g">Facebook</span>`,
       msg:`Sur facebook.com → « Créer un compte ». Ton vrai nom et l'email du projet.`,
       say:`Ce compte ne postera jamais rien. C'est ta clé d'entrée chez Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"🐙", kicker:"Ta clé n°4",
       title:`As-tu déjà un compte <span class="g">GitHub</span> ?`,
       say:`La plupart des gens n'en ont pas — c'est normal.`,
       btns:[{label:"✅ Oui", cls:"ghost", points:5, skip:1},{label:"❌ Non", cls:"ghost"}]},
      {type:'action', emoji:"🏢", kicker:"Mission · action",
       title:`Crée ton compte <span class="g">GitHub</span>`,
       msg:`Sur github.com → « Sign up ». Email du projet, mot de passe, plan gratuit (« Free »).`,
       say:`GitHub, c'est le bâtiment gratuit où vivront tes 3 robots.`,
       hint:`GitHub t'envoie un code à 8 chiffres par email — va le chercher.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔔", kicker:"Dernière clé",
       title:`Installe l'<span class="g">app GitHub</span> sur ton téléphone`,
       msg:`C'est ta télécommande : c'est là que tu diras « oui, publie ! ».`,
       say:`Quand elle demande les notifications, dis OUI — c'est le Messager !`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"🎯", kicker:"Récap",
       title:`Tes clés sont <span class="g">prêtes</span> !`,
       msg:`Email ✓ · Instagram pro ✓ · Facebook ✓ · GitHub ✓ · app mobile ✓`,
       say:`Le plus administratif est déjà derrière toi !`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 2 : Ton style ----------
  { id:2, title:"Ton style", sub:"Tes couleurs, ton logo, tes slides", emoji:"🎨",
    ready:true, badge:{emoji:"🖌️", name:"Artiste", bonus:55},
    steps:[
      {type:'story', emoji:"🎨", wiggle:true, kicker:"Chapitre 2",
       title:`On <span class="g">habille</span> ton usine`,
       msg:`Tu vas créer tes visuels de publication — sans Canva, sans logiciel compliqué.`,
       say:`Le secret : ton ordinateur dessine à ta place.`,
       btns:[{label:"Montre-moi", cls:"primary"}]},
      {type:'branch', emoji:"🌐", kicker:"Outil 1",
       title:`As-tu <span class="g">Google Chrome</span> sur ton ordinateur ?`,
       say:`C'est lui qui va « photographier » tes slides.`,
       btns:[{label:"✅ Oui", cls:"ghost", points:5, skip:1},{label:"❌ Non / je ne sais pas", cls:"ghost"}]},
      {type:'action', emoji:"🌐", kicker:"Mission · action",
       title:`Installe <span class="g">Google Chrome</span>`,
       msg:`Va sur google.com/chrome → « Télécharger » → installe (tout laisser par défaut).`,
       say:`Chrome sera ton photographe. Gratuit, évidemment.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"✍️", kicker:"Outil 2",
       title:`Installe <span class="g">VS Code</span>`,
       msg:`Sur code.visualstudio.com → « Download » → installe. C'est ton stylo pour changer quelques lignes.`,
       say:`Surtout pas Word ! Word casse les fichiers. VS Code est fait pour ça.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"🎨", kicker:"Ta marque",
       title:`Choisis tes <span class="g">4 couleurs</span>`,
       msg:`Un fond clair, un texte foncé, ta couleur de marque, et une couleur de bouton. C'est tout.`,
       say:`Astuce : prends les couleurs de ton logo ou de ton site.`,
       btns:[{label:"Compris", cls:"primary"}]},
      {type:'action', emoji:"🔢", kicker:"Mission · action",
       title:`Change les <span class="g">6 petites lignes</span>`,
       msg:`Dans le kit, ouvre le modèle avec VS Code. Tout en haut, il y a 6 lignes : tes 4 couleurs + ton @ Instagram + ton site. Change-les, enregistre. Rien d'autre !`,
       say:`6 lignes, pas une de plus. Promis.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🖼️", kicker:"Mission · action",
       title:`Mets <span class="g">ton logo</span>`,
       msg:`Remplace le fichier logo.png du kit par le tien (garde le même nom : logo.png).`,
       say:`Pas de logo ? Garde celui d'exemple, on verra plus tard.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"📸", kicker:"Le moment magique",
       title:`Le <span class="g">photographe</span> entre en scène`,
       msg:`Double-clique le fichier « GENERER » du kit. Une fenêtre noire clignote 2 secondes… et une image apparaît dans le dossier « rendu ». C'est ta slide !`,
       say:`Chrome vient de prendre en photo ta slide, à tes couleurs. Magique, non ?`,
       hint:`Mac : clic droit → Ouvrir la 1re fois (macOS protège les fichiers inconnus).`,
       btns:[{label:"Ma slide est apparue ✓", cls:"green", points:15}]},
      {type:'story', emoji:"✨", kicker:"Bravo",
       title:`Ta <span class="g">première slide</span> existe !`,
       msg:`À tes couleurs, avec ton logo, sans logiciel de design. Tu vois la puissance du truc ?`,
       say:`Le Dessinateur est prêt à travailler.`,
       btns:[{label:"Une dernière chose →", cls:"primary"}]},
      {type:'story', emoji:"📐", kicker:"La règle d'or",
       title:`Un bon carrousel = <span class="g">1 seule idée</span>`,
       msg:`Slide 1 : une promesse. Puis l'idée pas à pas. Avant la fin : une question quiz. Dernière : un petit récap.`,
       say:`Simple à retenir, simple à faire.`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 3 : Les clés magiques de Meta ----------
  { id:3, title:"Les clés magiques de Meta", sub:"Le sésame qui publie pour toi", emoji:"🗝️",
    ready:true, badge:{emoji:"🔓", name:"Passe-partout", bonus:80},
    steps:[
      {type:'story', emoji:"🏛️", wiggle:true, kicker:"Chapitre 3 · le grand boss",
       title:`Les <span class="g">autorisations</span> de Meta`,
       msg:`C'est LE chapitre que tout le monde rate. Mais pas toi : je reste avec toi à chaque guichet.`,
       say:`C'est de l'administratif — pas difficile, juste précis. Respire 😊`,
       btns:[{label:"Je suis prêt·e", cls:"primary"}]},
      {type:'story', emoji:"⚠️", kicker:"Le piège à connaître",
       title:`Ignore le <span class="g">bouton fantôme</span>`,
       msg:`Une page de Meta promet un bouton « Générer un token » qui n'apparaît jamais. Des gens y perdent des heures. Nous, on passe par la bonne porte : le Business Manager.`,
       say:`Si tu tombes sur cette page piège : ferme-la, reviens ici.`,
       btns:[{label:"Noté !", cls:"primary"}]},
      {type:'action', emoji:"📋", kicker:"Guichet 1",
       title:`Crée ton <span class="g">app Meta</span>`,
       msg:`Sur developers.facebook.com (connecté à Facebook) → « Créer une app » → cas d'usage « Instagram ».`,
       say:`C'est ton dossier officiel à la mairie Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🗄️", kicker:"Guichet 2",
       title:`Crée ton <span class="g">portefeuille business</span>`,
       msg:`Sur business.facebook.com → « Créer un compte » → nom de ton entreprise + email du projet.`,
       say:`C'est le classeur qui regroupe tout ce qui t'appartient chez Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔐", kicker:"Guichet 2 bis",
       title:`Active la <span class="g">double sécurité</span>`,
       msg:`Facebook → Paramètres → Sécurité → « Authentification à deux facteurs » → SMS → valide le code.`,
       say:`Meta l'exige pour confier des clés d'automatisation. Logique : ce sont les clés du camion.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"📷", kicker:"Guichet 3 · 🔑 clé 1/2",
       title:`<span class="g">Revendique</span> ton Instagram`,
       msg:`Business Manager → ⚙️ Paramètres → Comptes → Comptes Instagram → « Ajouter » → connecte @toncompte.`,
       say:`⚠️ Note bien le long numéro à 17 chiffres qui s'affiche — c'est ta 1re clé !`,
       btns:[{label:"Compte revendiqué + numéro noté ✓", cls:"green", points:15}]},
      {type:'action', emoji:"🤖", kicker:"Guichet 4",
       title:`Embauche ton <span class="g">facteur</span>`,
       msg:`⚙️ → Utilisateurs système → « Ajouter » → nom « Facteur » → puis « Affecter des éléments » : ton compte Instagram ET ton app.`,
       say:`C'est ton employé-robot officiel chez Meta.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"📄", kicker:"L'étape magique",
       title:`La <span class="g">Page Facebook</span>, l'adaptateur`,
       msg:`Meta oblige à passer par une Page Facebook (qui restera vide). Sans elle, le facteur reste à la porte.`,
       say:`C'est LA pièce que tout le monde oublie. Toi, tu la mets 😉`,
       btns:[{label:"On la crée", cls:"primary"}]},
      {type:'action', emoji:"🔗", kicker:"Guichet 5",
       title:`Crée la Page + <span class="g">lie-la</span> à Instagram`,
       msg:`Business Manager → Comptes → Pages → crée une Page. Puis dans l'app Instagram : Modifier le profil → Page → connecte ta Page.`,
       say:`Vérifie : dans les « éléments connectés » de la Page, ton Instagram apparaît. Le courant passe !`,
       btns:[{label:"Page créée et liée ✓", cls:"green", points:15}]},
      {type:'action', emoji:"🔑", kicker:"Guichet 6 · 🔑 clé 2/2",
       title:`Génère le <span class="g">token permanent</span>`,
       msg:`⚙️ → Utilisateurs système → Facteur → « Générer un token » → ton app → expiration « Jamais » → coche les 6 permissions → Générer → COPIE-le en lieu sûr.`,
       say:`Ce badge n'expire jamais. Configuré une fois, tranquille pour toujours 🎯`,
       btns:[{label:"Token généré et sauvegardé ✓", cls:"green", points:20}]},
      {type:'action', emoji:"🏆", kicker:"Le test de la victoire",
       title:`<span class="g">Teste</span> tes clés`,
       msg:`Double-clique « TESTER-TOKEN » du kit → colle ton token + ton numéro à 17 chiffres. Si tout est bon : ton nom de compte s'affiche + « quota : 0 ».`,
       say:`Si tu vois ton nom de compte : tu as réussi le plus dur. Chapeau !`,
       btns:[{label:"Ça affiche mon compte ✓", cls:"green", points:20}]},
      {type:'story', emoji:"🎉", kicker:"Énorme",
       title:`Tu as réussi ce que <span class="g">90 % abandonnent</span>`,
       msg:`Le plus dur est officiellement derrière toi. La suite, c'est de l'assemblage.`,
       say:`Je suis fier de toi. Vraiment.`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 4 : L'étagère à images ----------
  { id:4, title:"L'étagère à images", sub:"Héberger tes visuels, gratuitement", emoji:"📦",
    ready:true, badge:{emoji:"📚", name:"Rangé·e", bonus:45},
    steps:[
      {type:'story', emoji:"📦", wiggle:true, kicker:"Chapitre 4 · le plus court",
       title:`Un <span class="g">point de retrait</span> pour tes images`,
       msg:`Quand le facteur publie, Instagram veut aller chercher l'image lui-même, à une adresse. On lui crée cette étagère.`,
       say:`5 minutes, promis. Le chapitre le plus rapide.`,
       btns:[{label:"Allons-y", cls:"primary"}]},
      {type:'action', emoji:"📁", kicker:"Mission · action",
       title:`Crée un dépôt public <span class="g">« mes-images »</span>`,
       msg:`Sur github.com → bouton « + » → « New repository » → nom « mes-images » → coche « Public » et « Add a README » → Create.`,
       say:`« Dépôt » = un dossier hébergé sur internet. Rien de plus.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'story', emoji:"👁️", kicker:"Public, mais sans danger",
       title:`« Public », <span class="g">est-ce risqué</span> ? Non.`,
       msg:`On n'y met que des images en cours de publication — des images qui seront de toute façon publiques sur ton profil 10 secondes plus tard. Jamais de secret ici.`,
       say:`Tes clés, elles, ne vont JAMAIS ici. On les garde ailleurs.`,
       btns:[{label:"Rassuré·e", cls:"primary"}]},
      {type:'action', emoji:"🔗", kicker:"Petit test",
       title:`Teste une <span class="g">adresse d'image</span>`,
       msg:`Dans mes-images → « Add file » → glisse une image → « Commit ». Clique dessus → bouton « Raw » : l'image s'ouvre seule, avec une adresse. C'est ça qu'Instagram viendra chercher.`,
       say:`Ouvre cette adresse en navigation privée : elle s'affiche sans connexion. Parfait !`,
       btns:[{label:"L'image s'ouvre ✓", cls:"green", points:10}]},
      {type:'story', emoji:"✅", kicker:"Récap",
       title:`Ton étagère est <span class="g">ouverte</span>`,
       msg:`Le facteur saura où déposer les images pour qu'Instagram les récupère.`,
       say:`Prochain chapitre : ta toute première publication 🚀`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 5 : Ta première publication ----------
  { id:5, title:"Ta première publication", sub:"Le grand moment 🎉", emoji:"🚀",
    ready:true, badge:{emoji:"🥇", name:"Première fois", bonus:70},
    steps:[
      {type:'story', emoji:"⌨️", wiggle:true, kicker:"Chapitre 5 · le grand jour",
       title:`On apprivoise le <span class="g">terminal</span>`,
       msg:`Le terminal, c'est parler à ton ordinateur par écrit. Ça a l'air austère, mais c'est juste une conversation. Tu n'auras que 3 phrases à copier-coller.`,
       say:`Ça pique pas, promis. Je te tiens la main.`,
       btns:[{label:"Ouvrons-le", cls:"primary"}]},
      {type:'action', emoji:"⌨️", kicker:"Mission · action",
       title:`Ouvre le <span class="g">terminal</span> et dis bonjour`,
       msg:`Mac : Cmd+Espace → tape « Terminal » → Entrée. Windows : menu Démarrer → « PowerShell ». Puis tape : echo bonjour → Entrée.`,
       say:`L'ordinateur répond « bonjour ». Voilà, tu sais parler terminal 😄`,
       btns:[{label:"Il m'a répondu ✓", cls:"green", points:10}]},
      {type:'branch', emoji:"🐍", kicker:"Le moteur",
       title:`As-tu déjà utilisé <span class="g">Python</span> ou un terminal ?`,
       say:`Sur Mac, Python est souvent déjà installé.`,
       btns:[{label:"✅ Oui, à l'aise", cls:"ghost", points:5, skip:1},{label:"❌ Non", cls:"ghost"}]},
      {type:'action', emoji:"🐍", kicker:"Mission · action",
       title:`Installe <span class="g">Python</span>`,
       msg:`Mac : déjà là (tape python3 --version pour vérifier). Windows : python.org/downloads → ⚠️ COCHE « Add python.exe to PATH » avant d'installer.`,
       say:`Cette petite case sur Windows, c'est l'erreur n°1 des débutants. Ne l'oublie pas !`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔐", kicker:"Ton trousseau",
       title:`Range tes clés dans le <span class="g">trousseau</span>`,
       msg:`Dans le kit, ouvre « trousseau.env » avec VS Code. Colle ton token et ton identifiant à 17 chiffres (ceux du chapitre 3). Enregistre.`,
       say:`Ce fichier reste sur TON ordinateur. Ne le partage jamais.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🖼️", kicker:"Mission · action",
       title:`Génère les <span class="g">images</span> de l'exemple`,
       msg:`Le kit contient un carrousel d'exemple. Double-clique « GENERER » → les images apparaissent dans son dossier « rendu ».`,
       say:`Le Dessinateur au travail !`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"☁️", kicker:"Mission · action",
       title:`Mets-les sur ton <span class="g">étagère</span>`,
       msg:`Dans ton dépôt « mes-images » → « Add file » → glisse tout le contenu du dossier « rendu » → Commit.`,
       say:`(Au chapitre 6, les robots feront ça tout seuls — là, on apprend le geste une fois.)`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🧪", kicker:"Répétition à sec",
       title:`La <span class="g">répétition</span> (filet de sécurité)`,
       msg:`Dans le terminal, colle : python3 publier.py exemple-01 --repetition. Le facteur fait toute sa tournée… sauf publier. Rien n'apparaît sur Instagram.`,
       say:`On vérifie que tout est prêt AVANT le vrai lancement.`,
       btns:[{label:"« Tout est prêt » s'affiche ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🚀", kicker:"LE grand moment",
       title:`Ta <span class="g">première vraie publication</span> !`,
       msg:`Même commande, sans le filet : python3 publier.py exemple-01. Regarde le facteur travailler… « ✅ Publié ! »`,
       say:`Tu retiens ton souffle ? Moi aussi 🤖`,
       hint:`« Media ID is not available » = Meta digère, patiente, le script réessaie tout seul.`,
       btns:[{label:"« ✅ Publié ! » 🎉", cls:"green", points:25}]},
      {type:'story', emoji:"🎉", kicker:"REGARDE",
       title:`Ouvre Instagram… <span class="g">c'est en ligne !</span>`,
       msg:`Ton carrousel est sur ton profil. Publié par ton ordinateur, sans que tu touches Instagram. 🤯`,
       say:`Ton facteur est officiellement opérationnel !`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 6 : L'usine cloud ----------
  { id:6, title:"L'usine qui tourne seule", sub:"Ordinateur éteint, ça publie", emoji:"☁️",
    ready:true, badge:{emoji:"🏭", name:"Patron·ne d'usine", bonus:75},
    steps:[
      {type:'story', emoji:"☁️", wiggle:true, kicker:"Chapitre 6",
       title:`Ton ordinateur peut <span class="g">dormir</span>`,
       msg:`Jusqu'ici, le facteur travaille quand TU lances la commande. Maintenant, on déménage toute l'équipe chez GitHub. Ils travailleront même quand ton ordi est éteint.`,
       say:`GitHub prête des ordinateurs gratuits qui obéissent à un réveil-matin.`,
       btns:[{label:"On déménage !", cls:"primary"}]},
      {type:'action', emoji:"🏢", kicker:"Mission · action",
       title:`Crée le dépôt privé <span class="g">« mon-usine »</span>`,
       msg:`github.com → « + » → New repository → nom « mon-usine » → coche « Private » 🔒 → Create.`,
       say:`Privé : ta stratégie de contenu ne regarde personne.`,
       btns:[{label:"C'est fait ✓", cls:"green", points:10}]},
      {type:'action', emoji:"📤", kicker:"Mission · action",
       title:`Dépose les <span class="g">fichiers du kit</span>`,
       msg:`Dans « mon-usine » → Add file → Upload → glisse tout le contenu du kit… SAUF le fichier « trousseau.env » → Commit.`,
       say:`⚠️ Vérifie bien que « trousseau.env » n'est PAS dans la liste. C'est tes clés.`,
       btns:[{label:"C'est fait (sans le trousseau) ✓", cls:"green", points:10}]},
      {type:'action', emoji:"🔒", kicker:"Le coffre-fort",
       title:`Range tes clés dans les <span class="g">secrets</span>`,
       msg:`mon-usine → Settings → Secrets and variables → Actions → crée tes secrets (token, identifiant, étagère…), un par un, avec les noms exacts fournis.`,
       say:`Un coffre chiffré : les robots s'en servent, personne ne peut le relire.`,
       btns:[{label:"Secrets créés ✓", cls:"green", points:15}]},
      {type:'action', emoji:"🤖", kicker:"Mission · action",
       title:`Réveille tes <span class="g">robots</span>`,
       msg:`Onglet « Actions » de ton dépôt → si on te demande d'activer les workflows, clique. Puis lance un test : « Préparer le prochain carrousel » → Run workflow.`,
       say:`Rond jaune → coche verte = ton robot a travaillé tout seul !`,
       btns:[{label:"Le test passe au vert ✓", cls:"green", points:15}]},
      {type:'story', emoji:"📱", kicker:"Ding !",
       title:`Un <span class="g">ticket</span> arrive sur ton téléphone`,
       msg:`Le Messager t'envoie une notification : « Carrousel prêt ». Tu ouvres, tu vois les aperçus + la légende.`,
       say:`C'est le moment où TU décides. Depuis ton canapé.`,
       btns:[{label:"Je vois le ticket", cls:"primary"}]},
      {type:'action', emoji:"✅", kicker:"La magie",
       title:`Écris <span class="g">/publier</span> dans le ticket`,
       msg:`En bas du ticket, commente : /publier → envoie. 2 minutes plus tard : « ✅ Publié ! ». Et ton ordinateur est ÉTEINT.`,
       say:`Un ordinateur gratuit de GitHub vient de publier pour toi, puis s'est éteint. 🤯`,
       btns:[{label:"C'est publié, ordi éteint ✓", cls:"green", points:20}]},
      {type:'story', emoji:"🏭", kicker:"Énorme",
       title:`Ton usine est <span class="g">autonome</span> !`,
       msg:`Tous les 3 jours, elle prépare, te demande, et publie. Toi, tu valides depuis ton téléphone. En vacances, au ski, peu importe.`,
       say:`Tu es officiellement patron·ne d'usine 🏭`,
       btns:[{label:"Terminer le chapitre 🏆", cls:"green"}]},
    ]},

  // ---------- CHAPITRE 7 : Faire vivre ton usine ----------
  { id:7, title:"Faire vivre ton usine", sub:"Créer TON contenu · dépannage", emoji:"⚙️",
    ready:true, badge:{emoji:"🎓", name:"Diplômé·e", bonus:100},
    steps:[
      {type:'story', emoji:"⚙️", wiggle:true, kicker:"Dernier chapitre",
       title:`Le quotidien du <span class="g">patron</span>`,
       msg:`Ton usine tourne. Voyons comment la nourrir, la dépanner, et la garder en sécurité.`,
       say:`Le chapitre que tu rouvriras souvent. Gardons-le simple.`,
       btns:[{label:"C'est parti", cls:"primary"}]},
      {type:'story', emoji:"📓", kicker:"Le tableau de bord",
       title:`Le <span class="g">journal de production</span>`,
       msg:`Un fichier tenu à jour par les robots eux-mêmes : il dit où en est chaque carrousel (en file, en validation, publié). C'est la 1re chose à regarder.`,
       say:`« Où en est-on ? » → un coup d'œil au journal.`,
       btns:[{label:"Compris", cls:"primary"}]},
      {type:'action', emoji:"✍️", kicker:"Mission · action",
       title:`Crée <span class="g">TON</span> premier carrousel`,
       msg:`Duplique le dossier d'exemple, renomme-le, et change juste les textes de chaque slide (comme dans un formulaire). Dépose-le dans « mon-usine ». C'est tout !`,
       say:`Tu fournis les idées ; l'usine fait le design et la publication.`,
       btns:[{label:"J'ai créé mon carrousel ✓", cls:"green", points:15}]},
      {type:'story', emoji:"💡", kicker:"L'astuce qui va vite",
       title:`Fais-toi aider par une <span class="g">IA</span>`,
       msg:`Donne à un assistant IA (ChatGPT, Claude…) ta structure (promesse → idée → quiz → récap) + ton sujet, et il t'écrit les textes en 2 minutes. Tu gardes ton style.`,
       say:`Prépare 2-3 carrousels le dimanche : tu as une semaine d'avance.`,
       btns:[{label:"Bonne idée", cls:"primary"}]},
      {type:'story', emoji:"🛠️", kicker:"Pas de panique",
       title:`Les 5 <span class="g">pannes</span> classiques`,
       msg:`« Media ID not available » = patiente. Run rouge = souvent un secret mal orthographié. Pas de notif = réactive-les dans l'app. Le kit contient un tableau symptôme → remède.`,
       say:`Rien de ce que tu cliques ne casse définitivement. Le pire = régénérer un token (5 min).`,
       btns:[{label:"Rassurant", cls:"primary"}]},
      {type:'story', emoji:"📌", kicker:"La seule action manuelle",
       title:`Épingle le <span class="g">commentaire quiz</span>`,
       msg:`L'usine poste la réponse du quiz en commentaire, mais ne peut pas l'épingler. 10 secondes : appui long dessus → Épingler. Voilà.`,
       say:`La seule chose qui reste vraiment la tienne.`,
       btns:[{label:"Noté", cls:"primary"}]},
      {type:'story', emoji:"🔒", kicker:"Sécurité",
       title:`Les 4 <span class="g">commandements</span> des clés`,
       msg:`1) Ton token ne se partage jamais. 2) Il ne va jamais dans le dépôt public. 3) Un doute ? Révoque et régénère. 4) Double authentification active à vie.`,
       say:`« Le support Instagram » qui te demande ton token, c'est TOUJOURS une arnaque.`,
       btns:[{label:"Compris et retenu", cls:"primary"}]},
      {type:'story', emoji:"🎓", wiggle:true, kicker:"🏆 LA FIN",
       title:`Tu es <span class="g">diplômé·e</span> de l'usine !`,
       msg:`Ton compte publie désormais avec la régularité d'une horloge — et c'est exactement ce qu'Instagram récompense. Bravo, vraiment. À toi de jouer 🚀`,
       say:`J'ai adoré t'accompagner. Fier de toi ! — Nono 🤖`,
       btns:[{label:"Recevoir mon diplôme 🎓", cls:"green"}]},
    ]},

]};
